name: Robot Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install robotframework
        pip install robotframework-seleniumlibrary

    - name: Remove snap Firefox and install via apt (PPA)
      run: |
        # Remover Firefox via Snap, se estiver instalado
        sudo snap remove firefox || true

        # Adicionar o PPA da Mozilla
        sudo add-apt-repository ppa:mozillateam/ppa -y

        # Definir preferência do APT para usar o PPA
        echo '
        Package: firefox
        Pin: release o=LP-PPA-mozillateam
        Pin-Priority: 501
        ' | sudo tee /etc/apt/preferences.d/mozilla-firefox

        # Atualizar pacotes e instalar Firefox
        sudo apt-get update
        sudo apt-get install -y firefox

    - name: Install Firefox dependencies
      run: |
        sudo apt-get install -y libgtk-3-0 libdbus-glib-1-2 libxt6

    - name: Install GeckoDriver (stable version)
      run: |
        GECKODRIVER_VERSION=v0.34.0
        wget https://github.com/mozilla/geckodriver/releases/download/$GECKODRIVER_VERSION/geckodriver-$GECKODRIVER_VERSION-linux64.tar.gz
        tar -xvzf geckodriver-$GECKODRIVER_VERSION-linux64.tar.gz
        chmod +x geckodriver
        sudo mv geckodriver /usr/local/bin/

    - name: Run tests
      run: |
        robot Tests/
