name: Robot Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install robotframework
        pip install robotframework-seleniumlibrary

    - name: Remove snap Firefox and install via apt (PPA)
      run: |
        # Remover Firefox via Snap, se existir
        sudo snap remove firefox || true

        # Adicionar PPA oficial da Mozilla
        sudo add-apt-repository ppa:mozillateam/ppa -y

        # Criar preferência para o APT usar o Firefox do PPA, não o Snap
        echo '
        Package: firefox
        Pin: release o=LP-PPA-mozillateam
        Pin-Priority: 501
        ' | sudo tee /etc/apt/preferences.d/mozilla-firefox

        # Atualizar pacotes e instalar Firefox
        sudo apt-get update
        sudo apt-get install -y firefox

    - name: Install GeckoDriver
      run: |
        GECKODRIVER_VERSION=$(curl -s https://api.github.com/repos/mozilla/geckodriver/releases/latest | jq -r '.tag_name')
        wget https://github.com/mozilla/geckodriver/releases/download/$GECKODRIVER_VERSION/geckodriver-$GECKODRIVER_VERSION-linux64.tar.gz
        tar -xvzf geckodriver-$GECKODRIVER_VERSION-linux64.tar.gz
        chmod +x geckodriver
        sudo mv geckodriver /usr/local/bin/

    - name: Run tests
      run: |
        robot Tests/
